### ISSUE TITLE
Tests not running when upgrading to 0.82

### ISSUE THREAD

**Issue by Dambakk** [agensdev/darjeeling#6]
When upgrading from 0.81 to 0.82 the tests build successfully (after removing override on `setup` method), and gradle says its launching the tests, but no tests are run. The logcat contains the following error: 

```
2020-12-01 10:36:00.809 7009-7064/com.huma.app.dev E/AndroidRuntime: FATAL EXCEPTION: Instr: androidx.test.runner.AndroidJUnitRunner
    Process: com.huma.app.dev, PID: 7009
    java.lang.NoSuchMethodError: No virtual method shouldWaitForActivitiesToComplete()Z in class Landroidx/test/runner/AndroidJUnitRunner; or its super classes (declaration of ‘androidx.test.runner.AndroidJUnitRunner’ appears in /data/app/~~Od22jTsVpL7QTtuCwe3nDQ==/com.huma.app.dev.test-QqyDQ5yt45rSgPYLY2ejjg==/base.apk!classes3.dex)
        at androidx.test.runner.AndroidJUnitRunner.addListenersLegacyOrder(AndroidJUnitRunner.java:442)
        at androidx.test.runner.AndroidJUnitRunner.addListeners(AndroidJUnitRunner.java:423)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:391)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
```
The tests run fine when going back to 0.81.
